[package]
name = "omega-relay"
version = "0.1.0"
authors = ["Noah Huppert <contact@noahh.io>"]

[dependencies]
hyper = "0.12.12"
serde_json = "1.0.32"
futures = "0.1"
tokio = "0.1.11"
try_future = "0.1.3"
