[package]
name = "omega-relay"
version = "0.1.0"
authors = ["Noah Huppert <contact@noahh.io>"]

[dependencies]
serde_json = "1.0.32"
hyper = "0.12"
try_future = "0.1.3"
futures = "0.1.25"
tokio = "0.1.13"
tokio-core = "0.1.17"
